services:
  - type: web
    name: workout-planner-backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGODB_URI
        scope: build
      - key: JWT_SECRET_KEY
        scope: build
      - key: ALGORITHM
        scope: build
